// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2QUPGK6or3aF3adtYjGlQWWOFoXa19x4',
    appId: '1:386149399864:web:4d0bcd201a129a37bd55cd',
    messagingSenderId: '386149399864',
    projectId: 'roomfinder-kh',
    authDomain: 'roomfinder-kh.firebaseapp.com',
    storageBucket: 'roomfinder-kh.firebasestorage.app',
    measurementId: 'G-6DYBG1S9V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEW5ujSPaOPgvqVQQmJ5rUed943z0bnGU',
    appId: '1:386149399864:android:cc8f2ff76aec1b84bd55cd',
    messagingSenderId: '386149399864',
    projectId: 'roomfinder-kh',
    storageBucket: 'roomfinder-kh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvaxwSRtIJFTd-IaOYvBMCG3pqBS25jbg',
    appId: '1:386149399864:ios:7766c74d6054c973bd55cd',
    messagingSenderId: '386149399864',
    projectId: 'roomfinder-kh',
    storageBucket: 'roomfinder-kh.firebasestorage.app',
    iosBundleId: 'com.dinsarenkh.demoAccessRefreshTokenApp',
  );
}
